$(".owl-carousel").owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        }
    },
    autoplay:true,
    autoplayTimeout:6000,
    autoplaySpeed:3000,
    autoplayHoverPause:true
});
